version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      frequency: weekly
      day: monday
      time: "09:00"
      timezone: America/Sao_Paulo
    open-pull-requests-limit: 5
    versioning-strategy: increase-if-necessary
    groups:
      production-dependencies:
        dependency-type: production
        patterns:
          - "*"
      development-dependencies:
        dependency-type: development
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      frequency: weekly
      day: monday
      time: "09:30"
      timezone: America/Sao_Paulo
    open-pull-requests-limit: 3
